/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  CreateCompanyDto,
  EntitiesResponse,
  EntityResponse,
  ErrorResponse,
  NewEntityRequestReplyDto,
  RequestsResponse,
  SchoolEntitiesControllerGetMyPartnersParams,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const schoolEntitiesControllerGetMyPartners = (
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<EntitiesResponse>({
    url: `/api/school/entities/my-partners`,
    method: "GET",
    params,
    signal,
  });
};

export const getSchoolEntitiesControllerGetMyPartnersQueryKey = (
  params?: SchoolEntitiesControllerGetMyPartnersParams
) => {
  return [`/api/school/entities/my-partners`, ...(params ? [params] : [])] as const;
};

export const getSchoolEntitiesControllerGetMyPartnersQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSchoolEntitiesControllerGetMyPartnersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>
  > = ({ signal }) => schoolEntitiesControllerGetMyPartners(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetMyPartnersQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>
>;
export type SchoolEntitiesControllerGetMyPartnersQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetMyPartners<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params: undefined | SchoolEntitiesControllerGetMyPartnersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyPartners<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyPartners<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetMyPartners<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetMyPartnersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSchoolEntitiesControllerGetMyPartnersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSchoolEntitiesControllerGetMyPartnersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>
  > = ({ signal }) => schoolEntitiesControllerGetMyPartners(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetMyPartnersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>
>;
export type SchoolEntitiesControllerGetMyPartnersSuspenseQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetMyPartnersSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params: undefined | SchoolEntitiesControllerGetMyPartnersParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyPartnersSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyPartnersSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetMyPartnersSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
  TError = ErrorResponse,
>(
  params?: SchoolEntitiesControllerGetMyPartnersParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyPartners>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetMyPartnersSuspenseQueryOptions(
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const schoolEntitiesControllerGetMyRequests = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<RequestsResponse>({
    url: `/api/school/entities/requests`,
    method: "GET",
    signal,
  });
};

export const getSchoolEntitiesControllerGetMyRequestsQueryKey = () => {
  return [`/api/school/entities/requests`] as const;
};

export const getSchoolEntitiesControllerGetMyRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchoolEntitiesControllerGetMyRequestsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>
  > = ({ signal }) => schoolEntitiesControllerGetMyRequests(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetMyRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>
>;
export type SchoolEntitiesControllerGetMyRequestsQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetMyRequests<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyRequests<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyRequests<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetMyRequests<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetMyRequestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSchoolEntitiesControllerGetMyRequestsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchoolEntitiesControllerGetMyRequestsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>
  > = ({ signal }) => schoolEntitiesControllerGetMyRequests(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetMyRequestsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>
>;
export type SchoolEntitiesControllerGetMyRequestsSuspenseQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetMyRequestsSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyRequestsSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetMyRequestsSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetMyRequestsSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetMyRequests>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetMyRequestsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const schoolEntitiesControllerGetRequest = (
  id: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<RequestsResponse>({
    url: `/api/school/entities/requests/${id}`,
    method: "GET",
    signal,
  });
};

export const getSchoolEntitiesControllerGetRequestQueryKey = (id?: string | undefined | null) => {
  return [`/api/school/entities/requests/${id}`] as const;
};

export const getSchoolEntitiesControllerGetRequestQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchoolEntitiesControllerGetRequestQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>> = ({
    signal,
  }) => schoolEntitiesControllerGetRequest(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetRequestQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>
>;
export type SchoolEntitiesControllerGetRequestQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetRequest<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetRequest<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetRequest<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetRequest<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetRequestQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSchoolEntitiesControllerGetRequestSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchoolEntitiesControllerGetRequestQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>> = ({
    signal,
  }) => schoolEntitiesControllerGetRequest(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetRequestSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>
>;
export type SchoolEntitiesControllerGetRequestSuspenseQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetRequestSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetRequestSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetRequestSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetRequestSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetRequestSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const schoolEntitiesControllerApproveRequest = (
  id: string | undefined | null,
  newEntityRequestReplyDto: NewEntityRequestReplyDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/school/entities/requests/${id}/approve`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: newEntityRequestReplyDto,
    signal,
  });
};

export const getSchoolEntitiesControllerApproveRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerApproveRequest>>,
    TError,
    { id: string | undefined | null; data: NewEntityRequestReplyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schoolEntitiesControllerApproveRequest>>,
  TError,
  { id: string | undefined | null; data: NewEntityRequestReplyDto },
  TContext
> => {
  const mutationKey = ["schoolEntitiesControllerApproveRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerApproveRequest>>,
    { id: string | undefined | null; data: NewEntityRequestReplyDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return schoolEntitiesControllerApproveRequest(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SchoolEntitiesControllerApproveRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerApproveRequest>>
>;
export type SchoolEntitiesControllerApproveRequestMutationBody = NewEntityRequestReplyDto;
export type SchoolEntitiesControllerApproveRequestMutationError = ErrorResponse;

export const useSchoolEntitiesControllerApproveRequest = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schoolEntitiesControllerApproveRequest>>,
      TError,
      { id: string | undefined | null; data: NewEntityRequestReplyDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof schoolEntitiesControllerApproveRequest>>,
  TError,
  { id: string | undefined | null; data: NewEntityRequestReplyDto },
  TContext
> => {
  const mutationOptions = getSchoolEntitiesControllerApproveRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const schoolEntitiesControllerDenyRequest = (
  id: string | undefined | null,
  newEntityRequestReplyDto: NewEntityRequestReplyDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/school/entities/requests/${id}/deny`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: newEntityRequestReplyDto,
    signal,
  });
};

export const getSchoolEntitiesControllerDenyRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerDenyRequest>>,
    TError,
    { id: string | undefined | null; data: NewEntityRequestReplyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schoolEntitiesControllerDenyRequest>>,
  TError,
  { id: string | undefined | null; data: NewEntityRequestReplyDto },
  TContext
> => {
  const mutationKey = ["schoolEntitiesControllerDenyRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerDenyRequest>>,
    { id: string | undefined | null; data: NewEntityRequestReplyDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return schoolEntitiesControllerDenyRequest(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SchoolEntitiesControllerDenyRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerDenyRequest>>
>;
export type SchoolEntitiesControllerDenyRequestMutationBody = NewEntityRequestReplyDto;
export type SchoolEntitiesControllerDenyRequestMutationError = ErrorResponse;

export const useSchoolEntitiesControllerDenyRequest = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schoolEntitiesControllerDenyRequest>>,
      TError,
      { id: string | undefined | null; data: NewEntityRequestReplyDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof schoolEntitiesControllerDenyRequest>>,
  TError,
  { id: string | undefined | null; data: NewEntityRequestReplyDto },
  TContext
> => {
  const mutationOptions = getSchoolEntitiesControllerDenyRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const schoolEntitiesControllerBlacklistEntity = (
  entityId: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/school/entities/blacklist/${entityId}`,
    method: "POST",
    signal,
  });
};

export const getSchoolEntitiesControllerBlacklistEntityMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerBlacklistEntity>>,
    TError,
    { entityId: string | undefined | null },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schoolEntitiesControllerBlacklistEntity>>,
  TError,
  { entityId: string | undefined | null },
  TContext
> => {
  const mutationKey = ["schoolEntitiesControllerBlacklistEntity"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerBlacklistEntity>>,
    { entityId: string | undefined | null }
  > = (props) => {
    const { entityId } = props ?? {};

    return schoolEntitiesControllerBlacklistEntity(entityId);
  };

  return { mutationFn, ...mutationOptions };
};

export type SchoolEntitiesControllerBlacklistEntityMutationResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerBlacklistEntity>>
>;

export type SchoolEntitiesControllerBlacklistEntityMutationError = ErrorResponse;

export const useSchoolEntitiesControllerBlacklistEntity = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schoolEntitiesControllerBlacklistEntity>>,
      TError,
      { entityId: string | undefined | null },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof schoolEntitiesControllerBlacklistEntity>>,
  TError,
  { entityId: string | undefined | null },
  TContext
> => {
  const mutationOptions = getSchoolEntitiesControllerBlacklistEntityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const schoolEntitiesControllerGetAPartner = (
  id: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<EntityResponse>({
    url: `/api/school/entities/${id}`,
    method: "GET",
    signal,
  });
};

export const getSchoolEntitiesControllerGetAPartnerQueryKey = (id?: string | undefined | null) => {
  return [`/api/school/entities/${id}`] as const;
};

export const getSchoolEntitiesControllerGetAPartnerQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchoolEntitiesControllerGetAPartnerQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>> = ({
    signal,
  }) => schoolEntitiesControllerGetAPartner(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetAPartnerQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>
>;
export type SchoolEntitiesControllerGetAPartnerQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetAPartner<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetAPartner<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
          TError,
          Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetAPartner<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetAPartner<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetAPartnerQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSchoolEntitiesControllerGetAPartnerSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchoolEntitiesControllerGetAPartnerQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>> = ({
    signal,
  }) => schoolEntitiesControllerGetAPartner(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchoolEntitiesControllerGetAPartnerSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>
>;
export type SchoolEntitiesControllerGetAPartnerSuspenseQueryError = ErrorResponse;

export function useSchoolEntitiesControllerGetAPartnerSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetAPartnerSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSchoolEntitiesControllerGetAPartnerSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSchoolEntitiesControllerGetAPartnerSuspense<
  TData = Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof schoolEntitiesControllerGetAPartner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSchoolEntitiesControllerGetAPartnerSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const schoolEntitiesControllerCreateCompany = (
  createCompanyDto: CreateCompanyDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<EntityResponse>({
    url: `/api/school/entities`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createCompanyDto,
    signal,
  });
};

export const getSchoolEntitiesControllerCreateCompanyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schoolEntitiesControllerCreateCompany>>,
    TError,
    { data: CreateCompanyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schoolEntitiesControllerCreateCompany>>,
  TError,
  { data: CreateCompanyDto },
  TContext
> => {
  const mutationKey = ["schoolEntitiesControllerCreateCompany"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schoolEntitiesControllerCreateCompany>>,
    { data: CreateCompanyDto }
  > = (props) => {
    const { data } = props ?? {};

    return schoolEntitiesControllerCreateCompany(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SchoolEntitiesControllerCreateCompanyMutationResult = NonNullable<
  Awaited<ReturnType<typeof schoolEntitiesControllerCreateCompany>>
>;
export type SchoolEntitiesControllerCreateCompanyMutationBody = CreateCompanyDto;
export type SchoolEntitiesControllerCreateCompanyMutationError = ErrorResponse;

export const useSchoolEntitiesControllerCreateCompany = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof schoolEntitiesControllerCreateCompany>>,
      TError,
      { data: CreateCompanyDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof schoolEntitiesControllerCreateCompany>>,
  TError,
  { data: CreateCompanyDto },
  TContext
> => {
  const mutationOptions = getSchoolEntitiesControllerCreateCompanyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
