/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  CreateSignatoryResponse,
  ErrorResponse,
  FormGroupIdDto,
  FormGroupRemoveMemberDto,
  GetSignatoryFormSettingsRequest,
  GetSignatoryFormSettingsResponse,
  SetSignatoryFormSettingsRequest,
  SignatoryFormGroupMembersResponse,
  SignatoryFormGroupsResponse,
  SignatorySelfResponse,
  SignatorySignedFormsResponse,
  UpdateSignatoryDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const signatoryControllerGetSignatoryFormGroup = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me/form-group/__internal`,
    method: "POST",
    signal,
  });
};

export const getSignatoryControllerGetSignatoryFormGroupMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroup>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroup>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signatoryControllerGetSignatoryFormGroup"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroup>>,
    void
  > = () => {
    return signatoryControllerGetSignatoryFormGroup();
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerGetSignatoryFormGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroup>>
>;

export type SignatoryControllerGetSignatoryFormGroupMutationError = ErrorResponse;

export const useSignatoryControllerGetSignatoryFormGroup = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroup>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroup>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSignatoryControllerGetSignatoryFormGroupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerCreateAccountInternally = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CreateSignatoryResponse>({
    url: `/api/signatory/create/__internal`,
    method: "POST",
    signal,
  });
};

export const getSignatoryControllerCreateAccountInternallyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signatoryControllerCreateAccountInternally"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
    void
  > = () => {
    return signatoryControllerCreateAccountInternally();
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerCreateAccountInternallyMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>
>;

export type SignatoryControllerCreateAccountInternallyMutationError = ErrorResponse;

export const useSignatoryControllerCreateAccountInternally = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSignatoryControllerCreateAccountInternallyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSelf = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<SignatorySelfResponse>({
    url: `/api/signatory/me`,
    method: "GET",
    signal,
  });
};

export const getSignatoryControllerGetSelfQueryKey = () => {
  return [`/api/signatory/me`] as const;
};

export const getSignatoryControllerGetSelfQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSignatoryControllerGetSelfQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof signatoryControllerGetSelf>>> = ({
    signal,
  }) => signatoryControllerGetSelf(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSelfQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSelf>>
>;
export type SignatoryControllerGetSelfQueryError = ErrorResponse;

export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSelfQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryControllerGetSelfSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSignatoryControllerGetSelfQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof signatoryControllerGetSelf>>> = ({
    signal,
  }) => signatoryControllerGetSelf(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSelfSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSelf>>
>;
export type SignatoryControllerGetSelfSuspenseQueryError = ErrorResponse;

export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSelfSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signatoryControllerUpdateSelf = (updateSignatoryDto: UpdateSignatoryDto) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateSignatoryDto,
  });
};

export const getSignatoryControllerUpdateSelfMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
    TError,
    { data: UpdateSignatoryDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
  TError,
  { data: UpdateSignatoryDto },
  TContext
> => {
  const mutationKey = ["signatoryControllerUpdateSelf"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
    { data: UpdateSignatoryDto }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryControllerUpdateSelf(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerUpdateSelfMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>
>;
export type SignatoryControllerUpdateSelfMutationBody = UpdateSignatoryDto;
export type SignatoryControllerUpdateSelfMutationError = ErrorResponse;

export const useSignatoryControllerUpdateSelf = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
      TError,
      { data: UpdateSignatoryDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
  TError,
  { data: UpdateSignatoryDto },
  TContext
> => {
  const mutationOptions = getSignatoryControllerUpdateSelfMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSignatureInternally = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me/signature/__internal`,
    method: "POST",
    signal,
  });
};

export const getSignatoryControllerGetSignatureInternallyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatureInternally>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerGetSignatureInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signatoryControllerGetSignatureInternally"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatureInternally>>,
    void
  > = () => {
    return signatoryControllerGetSignatureInternally();
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerGetSignatureInternallyMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatureInternally>>
>;

export type SignatoryControllerGetSignatureInternallyMutationError = ErrorResponse;

export const useSignatoryControllerGetSignatureInternally = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignatureInternally>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerGetSignatureInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSignatoryControllerGetSignatureInternallyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSignedDocumentsBySignatory = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<SignatorySignedFormsResponse>({
    url: `/api/signatory/me/forms`,
    method: "GET",
    signal,
  });
};

export const getSignatoryControllerGetSignedDocumentsBySignatoryQueryKey = () => {
  return [`/api/signatory/me/forms`] as const;
};

export const getSignatoryControllerGetSignedDocumentsBySignatoryQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryControllerGetSignedDocumentsBySignatoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
  > = ({ signal }) => signatoryControllerGetSignedDocumentsBySignatory(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignedDocumentsBySignatoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
>;
export type SignatoryControllerGetSignedDocumentsBySignatoryQueryError = ErrorResponse;

export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSignedDocumentsBySignatoryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryControllerGetSignedDocumentsBySignatoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
  > = ({ signal }) => signatoryControllerGetSignedDocumentsBySignatory(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
>;
export type SignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryError = ErrorResponse;

export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getSignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signatoryControllerGetSignedDocumentsBySignatoryInternally = (
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<SignatorySignedFormsResponse>({
    url: `/api/signatory/me/forms/__internal`,
    method: "POST",
    signal,
  });
};

export const getSignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signatoryControllerGetSignedDocumentsBySignatoryInternally"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
    void
  > = () => {
    return signatoryControllerGetSignedDocumentsBySignatoryInternally();
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>
>;

export type SignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationError = ErrorResponse;

export const useSignatoryControllerGetSignedDocumentsBySignatoryInternally = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSignatoryFormGroups = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<SignatoryFormGroupsResponse>({
    url: `/api/signatory/me/form-groups`,
    method: "GET",
    signal,
  });
};

export const getSignatoryControllerGetSignatoryFormGroupsQueryKey = () => {
  return [`/api/signatory/me/form-groups`] as const;
};

export const getSignatoryControllerGetSignatoryFormGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSignatoryControllerGetSignatoryFormGroupsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>
  > = ({ signal }) => signatoryControllerGetSignatoryFormGroups(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignatoryFormGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>
>;
export type SignatoryControllerGetSignatoryFormGroupsQueryError = ErrorResponse;

export function useSignatoryControllerGetSignatoryFormGroups<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroups<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroups<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignatoryFormGroups<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSignatoryFormGroupsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryControllerGetSignatoryFormGroupsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSignatoryControllerGetSignatoryFormGroupsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>
  > = ({ signal }) => signatoryControllerGetSignatoryFormGroups(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignatoryFormGroupsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>
>;
export type SignatoryControllerGetSignatoryFormGroupsSuspenseQueryError = ErrorResponse;

export function useSignatoryControllerGetSignatoryFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignatoryFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSignatoryFormGroupsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signatoryControllerClearFormGroupMembers = (
  formGroupIdDto: FormGroupIdDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me/form-group/clear`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: formGroupIdDto,
    signal,
  });
};

export const getSignatoryControllerClearFormGroupMembersMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerClearFormGroupMembers>>,
    TError,
    { data: FormGroupIdDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerClearFormGroupMembers>>,
  TError,
  { data: FormGroupIdDto },
  TContext
> => {
  const mutationKey = ["signatoryControllerClearFormGroupMembers"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerClearFormGroupMembers>>,
    { data: FormGroupIdDto }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryControllerClearFormGroupMembers(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerClearFormGroupMembersMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerClearFormGroupMembers>>
>;
export type SignatoryControllerClearFormGroupMembersMutationBody = FormGroupIdDto;
export type SignatoryControllerClearFormGroupMembersMutationError = ErrorResponse;

export const useSignatoryControllerClearFormGroupMembers = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerClearFormGroupMembers>>,
      TError,
      { data: FormGroupIdDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerClearFormGroupMembers>>,
  TError,
  { data: FormGroupIdDto },
  TContext
> => {
  const mutationOptions = getSignatoryControllerClearFormGroupMembersMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerRemoveFormGroupMember = (
  formGroupRemoveMemberDto: FormGroupRemoveMemberDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me/form-group/remove`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: formGroupRemoveMemberDto,
    signal,
  });
};

export const getSignatoryControllerRemoveFormGroupMemberMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerRemoveFormGroupMember>>,
    TError,
    { data: FormGroupRemoveMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerRemoveFormGroupMember>>,
  TError,
  { data: FormGroupRemoveMemberDto },
  TContext
> => {
  const mutationKey = ["signatoryControllerRemoveFormGroupMember"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerRemoveFormGroupMember>>,
    { data: FormGroupRemoveMemberDto }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryControllerRemoveFormGroupMember(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerRemoveFormGroupMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerRemoveFormGroupMember>>
>;
export type SignatoryControllerRemoveFormGroupMemberMutationBody = FormGroupRemoveMemberDto;
export type SignatoryControllerRemoveFormGroupMemberMutationError = ErrorResponse;

export const useSignatoryControllerRemoveFormGroupMember = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerRemoveFormGroupMember>>,
      TError,
      { data: FormGroupRemoveMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerRemoveFormGroupMember>>,
  TError,
  { data: FormGroupRemoveMemberDto },
  TContext
> => {
  const mutationOptions = getSignatoryControllerRemoveFormGroupMemberMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSignatoryFormGroupMembers = (
  id: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<SignatoryFormGroupMembersResponse>({
    url: `/api/signatory/me/form-group/${id}`,
    method: "GET",
    signal,
  });
};

export const getSignatoryControllerGetSignatoryFormGroupMembersQueryKey = (
  id?: string | undefined | null
) => {
  return [`/api/signatory/me/form-group/${id}`] as const;
};

export const getSignatoryControllerGetSignatoryFormGroupMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryControllerGetSignatoryFormGroupMembersQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>
  > = ({ signal }) => signatoryControllerGetSignatoryFormGroupMembers(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignatoryFormGroupMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>
>;
export type SignatoryControllerGetSignatoryFormGroupMembersQueryError = ErrorResponse;

export function useSignatoryControllerGetSignatoryFormGroupMembers<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroupMembers<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroupMembers<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignatoryFormGroupMembers<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSignatoryFormGroupMembersQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryControllerGetSignatoryFormGroupMembersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryControllerGetSignatoryFormGroupMembersQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>
  > = ({ signal }) => signatoryControllerGetSignatoryFormGroupMembers(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignatoryFormGroupMembersSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>
>;
export type SignatoryControllerGetSignatoryFormGroupMembersSuspenseQueryError = ErrorResponse;

export function useSignatoryControllerGetSignatoryFormGroupMembersSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroupMembersSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignatoryFormGroupMembersSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignatoryFormGroupMembersSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormGroupMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSignatoryFormGroupMembersSuspenseQueryOptions(
    id,
    options
  );

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signatoryControllerGetSignatoryFormSettings = (
  getSignatoryFormSettingsRequest: GetSignatoryFormSettingsRequest,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<GetSignatoryFormSettingsResponse>({
    url: `/api/signatory/me/form-settings`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: getSignatoryFormSettingsRequest,
    signal,
  });
};

export const getSignatoryControllerGetSignatoryFormSettingsMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormSettings>>,
    TError,
    { data: GetSignatoryFormSettingsRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormSettings>>,
  TError,
  { data: GetSignatoryFormSettingsRequest },
  TContext
> => {
  const mutationKey = ["signatoryControllerGetSignatoryFormSettings"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormSettings>>,
    { data: GetSignatoryFormSettingsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryControllerGetSignatoryFormSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerGetSignatoryFormSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormSettings>>
>;
export type SignatoryControllerGetSignatoryFormSettingsMutationBody =
  GetSignatoryFormSettingsRequest;
export type SignatoryControllerGetSignatoryFormSettingsMutationError = ErrorResponse;

export const useSignatoryControllerGetSignatoryFormSettings = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormSettings>>,
      TError,
      { data: GetSignatoryFormSettingsRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerGetSignatoryFormSettings>>,
  TError,
  { data: GetSignatoryFormSettingsRequest },
  TContext
> => {
  const mutationOptions = getSignatoryControllerGetSignatoryFormSettingsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerSetSignatoryFormSettings = (
  setSignatoryFormSettingsRequest: SetSignatoryFormSettingsRequest
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me/form-settings`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: setSignatoryFormSettingsRequest,
  });
};

export const getSignatoryControllerSetSignatoryFormSettingsMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerSetSignatoryFormSettings>>,
    TError,
    { data: SetSignatoryFormSettingsRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerSetSignatoryFormSettings>>,
  TError,
  { data: SetSignatoryFormSettingsRequest },
  TContext
> => {
  const mutationKey = ["signatoryControllerSetSignatoryFormSettings"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerSetSignatoryFormSettings>>,
    { data: SetSignatoryFormSettingsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryControllerSetSignatoryFormSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerSetSignatoryFormSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerSetSignatoryFormSettings>>
>;
export type SignatoryControllerSetSignatoryFormSettingsMutationBody =
  SetSignatoryFormSettingsRequest;
export type SignatoryControllerSetSignatoryFormSettingsMutationError = ErrorResponse;

export const useSignatoryControllerSetSignatoryFormSettings = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerSetSignatoryFormSettings>>,
      TError,
      { data: SetSignatoryFormSettingsRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerSetSignatoryFormSettings>>,
  TError,
  { data: SetSignatoryFormSettingsRequest },
  TContext
> => {
  const mutationOptions = getSignatoryControllerSetSignatoryFormSettingsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
