/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type { SyncSingleFormDto } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const formSyncControllerCompareFormVersions = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<null>({ url: `/api/form-sync/compare`, method: "GET", signal });
};

export const getFormSyncControllerCompareFormVersionsQueryKey = () => {
  return [`/api/form-sync/compare`] as const;
};

export const getFormSyncControllerCompareFormVersionsQueryOptions = <
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFormSyncControllerCompareFormVersionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>
  > = ({ signal }) => formSyncControllerCompareFormVersions(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FormSyncControllerCompareFormVersionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>
>;
export type FormSyncControllerCompareFormVersionsQueryError = unknown;

export function useFormSyncControllerCompareFormVersions<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
          TError,
          Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormSyncControllerCompareFormVersions<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
          TError,
          Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormSyncControllerCompareFormVersions<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFormSyncControllerCompareFormVersions<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFormSyncControllerCompareFormVersionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFormSyncControllerCompareFormVersionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFormSyncControllerCompareFormVersionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>
  > = ({ signal }) => formSyncControllerCompareFormVersions(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FormSyncControllerCompareFormVersionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>
>;
export type FormSyncControllerCompareFormVersionsSuspenseQueryError = unknown;

export function useFormSyncControllerCompareFormVersionsSuspense<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormSyncControllerCompareFormVersionsSuspense<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormSyncControllerCompareFormVersionsSuspense<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFormSyncControllerCompareFormVersionsSuspense<
  TData = Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formSyncControllerCompareFormVersions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFormSyncControllerCompareFormVersionsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const formSyncControllerSyncAllForms = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<null>({ url: `/api/form-sync/sync`, method: "POST", signal });
};

export const getFormSyncControllerSyncAllFormsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof formSyncControllerSyncAllForms>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof formSyncControllerSyncAllForms>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["formSyncControllerSyncAllForms"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof formSyncControllerSyncAllForms>>,
    void
  > = () => {
    return formSyncControllerSyncAllForms();
  };

  return { mutationFn, ...mutationOptions };
};

export type FormSyncControllerSyncAllFormsMutationResult = NonNullable<
  Awaited<ReturnType<typeof formSyncControllerSyncAllForms>>
>;

export type FormSyncControllerSyncAllFormsMutationError = unknown;

export const useFormSyncControllerSyncAllForms = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof formSyncControllerSyncAllForms>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof formSyncControllerSyncAllForms>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getFormSyncControllerSyncAllFormsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const formSyncControllerSyncSingleForm = (
  syncSingleFormDto: SyncSingleFormDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<null>({
    url: `/api/form-sync/sync-single`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: syncSingleFormDto,
    signal,
  });
};

export const getFormSyncControllerSyncSingleFormMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof formSyncControllerSyncSingleForm>>,
    TError,
    { data: SyncSingleFormDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof formSyncControllerSyncSingleForm>>,
  TError,
  { data: SyncSingleFormDto },
  TContext
> => {
  const mutationKey = ["formSyncControllerSyncSingleForm"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof formSyncControllerSyncSingleForm>>,
    { data: SyncSingleFormDto }
  > = (props) => {
    const { data } = props ?? {};

    return formSyncControllerSyncSingleForm(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FormSyncControllerSyncSingleFormMutationResult = NonNullable<
  Awaited<ReturnType<typeof formSyncControllerSyncSingleForm>>
>;
export type FormSyncControllerSyncSingleFormMutationBody = SyncSingleFormDto;
export type FormSyncControllerSyncSingleFormMutationError = unknown;

export const useFormSyncControllerSyncSingleForm = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof formSyncControllerSyncSingleForm>>,
      TError,
      { data: SyncSingleFormDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof formSyncControllerSyncSingleForm>>,
  TError,
  { data: SyncSingleFormDto },
  TContext
> => {
  const mutationOptions = getFormSyncControllerSyncSingleFormMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
