/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type { ErrorResponse, QueryDocResponse, SignatoryFormtemplatesResponse } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const docsControllerGetByVerificationCode = (
  code: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<QueryDocResponse>({
    url: `/api/docs/query/${code}`,
    method: "GET",
    signal,
  });
};

export const getDocsControllerGetByVerificationCodeQueryKey = (
  code?: string | undefined | null
) => {
  return [`/api/docs/query/${code}`] as const;
};

export const getDocsControllerGetByVerificationCodeQueryOptions = <
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDocsControllerGetByVerificationCodeQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>> = ({
    signal,
  }) => docsControllerGetByVerificationCode(code, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DocsControllerGetByVerificationCodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>
>;
export type DocsControllerGetByVerificationCodeQueryError = ErrorResponse;

export function useDocsControllerGetByVerificationCode<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
          TError,
          Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetByVerificationCode<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
          TError,
          Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetByVerificationCode<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDocsControllerGetByVerificationCode<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDocsControllerGetByVerificationCodeQueryOptions(code, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDocsControllerGetByVerificationCodeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDocsControllerGetByVerificationCodeQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>> = ({
    signal,
  }) => docsControllerGetByVerificationCode(code, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DocsControllerGetByVerificationCodeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>
>;
export type DocsControllerGetByVerificationCodeSuspenseQueryError = ErrorResponse;

export function useDocsControllerGetByVerificationCodeSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetByVerificationCodeSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetByVerificationCodeSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDocsControllerGetByVerificationCodeSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
  TError = ErrorResponse,
>(
  code: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetByVerificationCode>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDocsControllerGetByVerificationCodeSuspenseQueryOptions(code, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const docsControllerResolveUrl = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<unknown>({
    url: `/api/docs/resolve-url`,
    method: "POST",
    signal,
  });
};

export const getDocsControllerResolveUrlMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof docsControllerResolveUrl>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof docsControllerResolveUrl>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["docsControllerResolveUrl"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof docsControllerResolveUrl>>,
    void
  > = () => {
    return docsControllerResolveUrl();
  };

  return { mutationFn, ...mutationOptions };
};

export type DocsControllerResolveUrlMutationResult = NonNullable<
  Awaited<ReturnType<typeof docsControllerResolveUrl>>
>;

export type DocsControllerResolveUrlMutationError = ErrorResponse;

export const useDocsControllerResolveUrl = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof docsControllerResolveUrl>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof docsControllerResolveUrl>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDocsControllerResolveUrlMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const docsControllerResolveUrlInternal = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<unknown>({
    url: `/api/docs/resolve-url/__internal`,
    method: "POST",
    signal,
  });
};

export const getDocsControllerResolveUrlInternalMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof docsControllerResolveUrlInternal>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof docsControllerResolveUrlInternal>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["docsControllerResolveUrlInternal"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof docsControllerResolveUrlInternal>>,
    void
  > = () => {
    return docsControllerResolveUrlInternal();
  };

  return { mutationFn, ...mutationOptions };
};

export type DocsControllerResolveUrlInternalMutationResult = NonNullable<
  Awaited<ReturnType<typeof docsControllerResolveUrlInternal>>
>;

export type DocsControllerResolveUrlInternalMutationError = ErrorResponse;

export const useDocsControllerResolveUrlInternal = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof docsControllerResolveUrlInternal>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof docsControllerResolveUrlInternal>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDocsControllerResolveUrlInternalMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const docsControllerGetEntityForms = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<SignatoryFormtemplatesResponse>({
    url: `/api/docs/entity-forms`,
    method: "GET",
    signal,
  });
};

export const getDocsControllerGetEntityFormsQueryKey = () => {
  return [`/api/docs/entity-forms`] as const;
};

export const getDocsControllerGetEntityFormsQueryOptions = <
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof docsControllerGetEntityForms>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDocsControllerGetEntityFormsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof docsControllerGetEntityForms>>> = ({
    signal,
  }) => docsControllerGetEntityForms(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DocsControllerGetEntityFormsQueryResult = NonNullable<
  Awaited<ReturnType<typeof docsControllerGetEntityForms>>
>;
export type DocsControllerGetEntityFormsQueryError = ErrorResponse;

export function useDocsControllerGetEntityForms<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsControllerGetEntityForms>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
          TError,
          Awaited<ReturnType<typeof docsControllerGetEntityForms>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetEntityForms<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsControllerGetEntityForms>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
          TError,
          Awaited<ReturnType<typeof docsControllerGetEntityForms>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetEntityForms<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsControllerGetEntityForms>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDocsControllerGetEntityForms<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsControllerGetEntityForms>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDocsControllerGetEntityFormsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDocsControllerGetEntityFormsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof docsControllerGetEntityForms>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDocsControllerGetEntityFormsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof docsControllerGetEntityForms>>> = ({
    signal,
  }) => docsControllerGetEntityForms(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DocsControllerGetEntityFormsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof docsControllerGetEntityForms>>
>;
export type DocsControllerGetEntityFormsSuspenseQueryError = ErrorResponse;

export function useDocsControllerGetEntityFormsSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetEntityFormsSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsControllerGetEntityFormsSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDocsControllerGetEntityFormsSuspense<
  TData = Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsControllerGetEntityForms>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDocsControllerGetEntityFormsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
