/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface _FormGroup {
  id: string;
  description: string;
  /** @nullable */
  code: string | null;
  /** @nullable */
  coordinator_id: string | null;
  forms: string[];
}
