/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface _FormGroupMember {
  id: string;
  name: string;
  email: string;
  joinedAt: string;
}
