/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { ContactDto } from "./contactDto";
import type { ProfileDto } from "./profileDto";

export interface CreateCompanyDto {
  display_name: string;
  legal_name: string;
  office_location: string;
  industry: string;
  contact: ContactDto;
  profile?: ProfileDto;
  password: string;
  type?: string;
}
