/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { PublicEntityDto } from "./publicEntityDto";

export interface EntitiesResponse {
  success: boolean;
  message: string;
  entities: PublicEntityDto[];
}
