/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { ExportableFormDtoInputs } from "./exportableFormDtoInputs";
import type { ExportableFormDtoSigningPartiesItem } from "./exportableFormDtoSigningPartiesItem";

export interface ExportableFormDto {
  id: string;
  status: string;
  inputs: ExportableFormDtoInputs;
  signingParties: ExportableFormDtoSigningPartiesItem[];
  formLabel: string;
  formName: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  documentUrl: string | null;
}
