/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind =
  (typeof FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind)[keyof typeof FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind = {
  array: "array",
} as const;
