/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind";

export type FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezero = {
  kind: FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezeroKind;
  options: string[];
  minItems?: number;
  maxItems?: number;
  minMessage?: string;
  maxMessage?: string;
};
