/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type FieldRegistryEntryDetailsFieldSchemaDefaultsAlignV =
  (typeof FieldRegistryEntryDetailsFieldSchemaDefaultsAlignV)[keyof typeof FieldRegistryEntryDetailsFieldSchemaDefaultsAlignV];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldRegistryEntryDetailsFieldSchemaDefaultsAlignV = {
  top: "top",
  middle: "middle",
  bottom: "bottom",
} as const;
