/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOf } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOf";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfThree } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfThree";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfSix } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfSix";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfEight } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfEight";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezero } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezero";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnetwo } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnetwo";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnefour } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnefour";

export type FieldRegistryEntryDetailsValidatorIrRulesItem =
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOf
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOfThree
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOfSix
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOfEight
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnezero
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnetwo
  | FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnefour;
