/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormFieldValidatorIrRulesItemOneOfEightKind } from "./formFieldValidatorIrRulesItemOneOfEightKind";

export type FormFieldValidatorIrRulesItemOneOfEight = {
  kind: FormFieldValidatorIrRulesItemOneOfEightKind;
  options: string[];
  message?: string;
};
