/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type FormPhantomFieldValidatorIrVersion =
  (typeof FormPhantomFieldValidatorIrVersion)[keyof typeof FormPhantomFieldValidatorIrVersion];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormPhantomFieldValidatorIrVersion = {
  NUMBER_0: 0,
} as const;
