/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormProcessDisplayInformation } from "./formProcessDisplayInformation";
import type { SigningParty } from "./signingParty";

export interface FormProcess {
  prefilled_document_id: string;
  pending_document_id: string;
  signed_document_id: string;
  latest_document_url: string;
  rejection_reason: string;
  display_information: FormProcessDisplayInformation;
  signing_parties: SigningParty[];
}
