/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type FormFieldValidatorIrRulesItemOneOfThreeKind =
  (typeof FormFieldValidatorIrRulesItemOneOfThreeKind)[keyof typeof FormFieldValidatorIrRulesItemOneOfThreeKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormFieldValidatorIrRulesItemOneOfThreeKind = {
  minLength: "minLength",
  maxLength: "maxLength",
  min: "min",
  max: "max",
  minTime: "minTime",
  maxTime: "maxTime",
} as const;
