/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnezeroKind } from "./formPhantomFieldValidatorIrRulesItemOneOfOnezeroKind";

export type FormPhantomFieldValidatorIrRulesItemOneOfOnezero = {
  kind: FormPhantomFieldValidatorIrRulesItemOneOfOnezeroKind;
  options: string[];
  minItems?: number;
  maxItems?: number;
  minMessage?: string;
  maxMessage?: string;
};
