/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormBlockBlockType } from "./formBlockBlockType";
import type { FormField } from "./formField";
import type { FormPhantomField } from "./formPhantomField";

export interface FormBlock {
  _id: string;
  block_type: FormBlockBlockType;
  order: number;
  signing_party_id: string;
  text_content?: string;
  field_schema: FormField;
  phantom_field_schema: FormPhantomField;
}
