/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormProcessDtoDisplayInformation } from "./formProcessDtoDisplayInformation";

export interface FormProcessDto {
  my_signing_party_id: string;
  display_information: FormProcessDtoDisplayInformation;
  form_label: string;
  form_name: string;
  form_version: number;
  schema_version: number;
  latest_document_url: string;
  prefilled_document_id: string;
  signed_document_id: string;
  timestamp: string;
}
