/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type FormPhantomFieldValidatorIrImportStatus =
  (typeof FormPhantomFieldValidatorIrImportStatus)[keyof typeof FormPhantomFieldValidatorIrImportStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormPhantomFieldValidatorIrImportStatus = {
  exact: "exact",
  partial: "partial",
  custom: "custom",
} as const;
