/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormFieldValidatorIrRulesItemOneOf } from "./formFieldValidatorIrRulesItemOneOf";
import type { FormFieldValidatorIrRulesItemOneOfThree } from "./formFieldValidatorIrRulesItemOneOfThree";
import type { FormFieldValidatorIrRulesItemOneOfSix } from "./formFieldValidatorIrRulesItemOneOfSix";
import type { FormFieldValidatorIrRulesItemOneOfEight } from "./formFieldValidatorIrRulesItemOneOfEight";
import type { FormFieldValidatorIrRulesItemOneOfOnezero } from "./formFieldValidatorIrRulesItemOneOfOnezero";
import type { FormFieldValidatorIrRulesItemOneOfOnetwo } from "./formFieldValidatorIrRulesItemOneOfOnetwo";
import type { FormFieldValidatorIrRulesItemOneOfOnefour } from "./formFieldValidatorIrRulesItemOneOfOnefour";

export type FormFieldValidatorIrRulesItem =
  | FormFieldValidatorIrRulesItemOneOf
  | FormFieldValidatorIrRulesItemOneOfThree
  | FormFieldValidatorIrRulesItemOneOfSix
  | FormFieldValidatorIrRulesItemOneOfEight
  | FormFieldValidatorIrRulesItemOneOfOnezero
  | FormFieldValidatorIrRulesItemOneOfOnetwo
  | FormFieldValidatorIrRulesItemOneOfOnefour;
