/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormPhantomFieldType } from "./formPhantomFieldType";
import type { FormPhantomFieldSource } from "./formPhantomFieldSource";
import type { FormPhantomFieldValidatorIr } from "./formPhantomFieldValidatorIr";

export interface FormPhantomField {
  field: string;
  type: FormPhantomFieldType;
  label: string;
  tooltip_label: string;
  shared: boolean;
  signing_party_id: string;
  source: FormPhantomFieldSource;
  prefiller: string;
  validator: string;
  /** @nullable */
  validator_ir?: FormPhantomFieldValidatorIr;
}
