/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormProcessDto } from "./formProcessDto";

export interface FormProcessResponse {
  success: boolean;
  message: string;
  formProcess: FormProcessDto;
}
