/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormFieldType } from "./formFieldType";
import type { FormFieldSource } from "./formFieldSource";
import type { FormFieldValidatorIr } from "./formFieldValidatorIr";

export interface FormField {
  field: string;
  type: FormFieldType;
  x: number;
  y: number;
  w: number;
  h: number;
  page: number;
  label: string;
  tooltip_label: string;
  shared: boolean;
  signing_party_id: string;
  source: FormFieldSource;
  prefiller: string;
  validator: string;
  /** @nullable */
  validator_ir?: FormFieldValidatorIr;
}
