/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormPhantomFieldValidatorIrRulesItemOneOf } from "./formPhantomFieldValidatorIrRulesItemOneOf";
import type { FormPhantomFieldValidatorIrRulesItemOneOfThree } from "./formPhantomFieldValidatorIrRulesItemOneOfThree";
import type { FormPhantomFieldValidatorIrRulesItemOneOfSix } from "./formPhantomFieldValidatorIrRulesItemOneOfSix";
import type { FormPhantomFieldValidatorIrRulesItemOneOfEight } from "./formPhantomFieldValidatorIrRulesItemOneOfEight";
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnezero } from "./formPhantomFieldValidatorIrRulesItemOneOfOnezero";
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnetwo } from "./formPhantomFieldValidatorIrRulesItemOneOfOnetwo";
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnefour } from "./formPhantomFieldValidatorIrRulesItemOneOfOnefour";

export type FormPhantomFieldValidatorIrRulesItem =
  | FormPhantomFieldValidatorIrRulesItemOneOf
  | FormPhantomFieldValidatorIrRulesItemOneOfThree
  | FormPhantomFieldValidatorIrRulesItemOneOfSix
  | FormPhantomFieldValidatorIrRulesItemOneOfEight
  | FormPhantomFieldValidatorIrRulesItemOneOfOnezero
  | FormPhantomFieldValidatorIrRulesItemOneOfOnetwo
  | FormPhantomFieldValidatorIrRulesItemOneOfOnefour;
