/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface FormTemplate {
  name: string;
  label: string;
  version: number;
  base_document_id: string;
  time_generated: string;
}
