/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface NewStandardMoaRequestDto {
  school_id: string;
  entity_signatory_name: string;
  entity_signatory_title: string;
}
