/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { PublicEntityDtoDisplayName } from "./publicEntityDtoDisplayName";
import type { PublicEntityDtoType } from "./publicEntityDtoType";
import type { PublicEntityDtoContactName } from "./publicEntityDtoContactName";
import type { PublicEntityDtoContactEmail } from "./publicEntityDtoContactEmail";
import type { PublicEntityDtoContactPhone } from "./publicEntityDtoContactPhone";
import type { PublicEntityDtoAddress } from "./publicEntityDtoAddress";

export interface PublicEntityDto {
  id: string;
  /** @nullable */
  display_name: PublicEntityDtoDisplayName;
  legal_identifier: string;
  type: PublicEntityDtoType;
  contact_name?: PublicEntityDtoContactName;
  contact_email?: PublicEntityDtoContactEmail;
  contact_phone?: PublicEntityDtoContactPhone;
  address?: PublicEntityDtoAddress;
}
