/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type RegisterFieldDtoValidatorIrImportStatus =
  (typeof RegisterFieldDtoValidatorIrImportStatus)[keyof typeof RegisterFieldDtoValidatorIrImportStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterFieldDtoValidatorIrImportStatus = {
  exact: "exact",
  partial: "partial",
  custom: "custom",
} as const;
