/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { RegisterFieldDtoFieldSchemaDefaultsAlignH } from "./registerFieldDtoFieldSchemaDefaultsAlignH";
import type { RegisterFieldDtoFieldSchemaDefaultsAlignV } from "./registerFieldDtoFieldSchemaDefaultsAlignV";

/**
 * @nullable
 */
export type RegisterFieldDtoFieldSchemaDefaults = {
  w?: number;
  h?: number;
  wrap?: boolean;
  size?: number;
  align_h?: RegisterFieldDtoFieldSchemaDefaultsAlignH;
  align_v?: RegisterFieldDtoFieldSchemaDefaultsAlignV;
  font?: string;
} | null;
