/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { RegisterFieldDtoValidatorIrRulesItemOneOfThreeKind } from "./registerFieldDtoValidatorIrRulesItemOneOfThreeKind";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfThreeValue } from "./registerFieldDtoValidatorIrRulesItemOneOfThreeValue";

export type RegisterFieldDtoValidatorIrRulesItemOneOfThree = {
  kind: RegisterFieldDtoValidatorIrRulesItemOneOfThreeKind;
  value: RegisterFieldDtoValidatorIrRulesItemOneOfThreeValue;
  message?: string;
};
