/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { RegisterFieldDtoValidatorIrRulesItemOneOf } from "./registerFieldDtoValidatorIrRulesItemOneOf";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfThree } from "./registerFieldDtoValidatorIrRulesItemOneOfThree";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfSix } from "./registerFieldDtoValidatorIrRulesItemOneOfSix";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfEight } from "./registerFieldDtoValidatorIrRulesItemOneOfEight";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnezero } from "./registerFieldDtoValidatorIrRulesItemOneOfOnezero";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnetwo } from "./registerFieldDtoValidatorIrRulesItemOneOfOnetwo";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnefour } from "./registerFieldDtoValidatorIrRulesItemOneOfOnefour";

export type RegisterFieldDtoValidatorIrRulesItem =
  | RegisterFieldDtoValidatorIrRulesItemOneOf
  | RegisterFieldDtoValidatorIrRulesItemOneOfThree
  | RegisterFieldDtoValidatorIrRulesItemOneOfSix
  | RegisterFieldDtoValidatorIrRulesItemOneOfEight
  | RegisterFieldDtoValidatorIrRulesItemOneOfOnezero
  | RegisterFieldDtoValidatorIrRulesItemOneOfOnetwo
  | RegisterFieldDtoValidatorIrRulesItemOneOfOnefour;
