/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type RegisterFieldDtoFieldSchemaDefaultsAlignH =
  (typeof RegisterFieldDtoFieldSchemaDefaultsAlignH)[keyof typeof RegisterFieldDtoFieldSchemaDefaultsAlignH];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterFieldDtoFieldSchemaDefaultsAlignH = {
  left: "left",
  center: "center",
  right: "right",
} as const;
