/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { RegisterFieldDtoSource } from "./registerFieldDtoSource";
import type { RegisterFieldDtoValidatorIr } from "./registerFieldDtoValidatorIr";
import type { RegisterFieldDtoFieldSchemaDefaults } from "./registerFieldDtoFieldSchemaDefaults";

export interface RegisterFieldDto {
  name: string;
  label: string;
  type: string;
  party: string;
  shared: boolean;
  source: RegisterFieldDtoSource;
  tag: string;
  /** @nullable */
  prefiller: string | null;
  preset: string;
  /** @nullable */
  tooltip_label: string | null;
  /** @nullable */
  validator: string | null;
  /** @nullable */
  validator_ir?: RegisterFieldDtoValidatorIr;
  /** @nullable */
  field_schema_defaults: RegisterFieldDtoFieldSchemaDefaults;
  is_phantom: boolean;
}
