/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnezeroKind } from "./registerFieldDtoValidatorIrRulesItemOneOfOnezeroKind";

export type RegisterFieldDtoValidatorIrRulesItemOneOfOnezero = {
  kind: RegisterFieldDtoValidatorIrRulesItemOneOfOnezeroKind;
  options: string[];
  minItems?: number;
  maxItems?: number;
  minMessage?: string;
  maxMessage?: string;
};
