/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { SelfSchoolResponseSchool } from "./selfSchoolResponseSchool";
import type { SelfSchoolResponseSchoolAccount } from "./selfSchoolResponseSchoolAccount";

export interface SelfSchoolResponse {
  success: boolean;
  message: string;
  school: SelfSchoolResponseSchool;
  schoolAccount: SelfSchoolResponseSchoolAccount;
}
