/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface SignCustomMoaRequestDto {
  entity_id: string;
  request_id: string;
  additional_form_schema: string[];
}
