/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { SignatoryInfo } from "./signatoryInfo";

export interface SignedOrExternalDocumentInfo {
  url: string;
  signatories: SignatoryInfo[];
  date_made: string;
  form_label: string;
  uploaded_at: string;
  verification_code: string;
  code: string;
}
