/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { UpdateFieldDtoValidatorIrRulesItemOneOfKind } from "./updateFieldDtoValidatorIrRulesItemOneOfKind";

export type UpdateFieldDtoValidatorIrRulesItemOneOf = {
  kind: UpdateFieldDtoValidatorIrRulesItemOneOfKind;
  message?: string;
};
