/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { UpdateFieldDtoFieldSchemaDefaultsAlignH } from "./updateFieldDtoFieldSchemaDefaultsAlignH";
import type { UpdateFieldDtoFieldSchemaDefaultsAlignV } from "./updateFieldDtoFieldSchemaDefaultsAlignV";

/**
 * @nullable
 */
export type UpdateFieldDtoFieldSchemaDefaults = {
  w?: number;
  h?: number;
  wrap?: boolean;
  size?: number;
  align_h?: UpdateFieldDtoFieldSchemaDefaultsAlignH;
  align_v?: UpdateFieldDtoFieldSchemaDefaultsAlignV;
  font?: string;
} | null;
