/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { UpdateFieldDtoSource } from "./updateFieldDtoSource";
import type { UpdateFieldDtoValidatorIr } from "./updateFieldDtoValidatorIr";
import type { UpdateFieldDtoFieldSchemaDefaults } from "./updateFieldDtoFieldSchemaDefaults";

export interface UpdateFieldDto {
  id: string;
  name: string;
  label: string;
  type: string;
  shared: boolean;
  party: string;
  source: UpdateFieldDtoSource;
  tag: string;
  /** @nullable */
  prefiller: string | null;
  preset: string;
  /** @nullable */
  tooltip_label: string | null;
  /** @nullable */
  validator: string | null;
  /** @nullable */
  validator_ir?: UpdateFieldDtoValidatorIr;
  /** @nullable */
  field_schema_defaults: UpdateFieldDtoFieldSchemaDefaults;
  is_phantom: boolean;
}
