/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type UpdateFieldDtoFieldSchemaDefaultsAlignH =
  (typeof UpdateFieldDtoFieldSchemaDefaultsAlignH)[keyof typeof UpdateFieldDtoFieldSchemaDefaultsAlignH];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFieldDtoFieldSchemaDefaultsAlignH = {
  left: "left",
  center: "center",
  right: "right",
} as const;
