/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { UpdateFieldDtoValidatorIrRulesItemOneOf } from "./updateFieldDtoValidatorIrRulesItemOneOf";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfThree } from "./updateFieldDtoValidatorIrRulesItemOneOfThree";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfSix } from "./updateFieldDtoValidatorIrRulesItemOneOfSix";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfEight } from "./updateFieldDtoValidatorIrRulesItemOneOfEight";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfOnezero } from "./updateFieldDtoValidatorIrRulesItemOneOfOnezero";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfOnetwo } from "./updateFieldDtoValidatorIrRulesItemOneOfOnetwo";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfOnefour } from "./updateFieldDtoValidatorIrRulesItemOneOfOnefour";

export type UpdateFieldDtoValidatorIrRulesItem =
  | UpdateFieldDtoValidatorIrRulesItemOneOf
  | UpdateFieldDtoValidatorIrRulesItemOneOfThree
  | UpdateFieldDtoValidatorIrRulesItemOneOfSix
  | UpdateFieldDtoValidatorIrRulesItemOneOfEight
  | UpdateFieldDtoValidatorIrRulesItemOneOfOnezero
  | UpdateFieldDtoValidatorIrRulesItemOneOfOnetwo
  | UpdateFieldDtoValidatorIrRulesItemOneOfOnefour;
