/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type UpdateFieldDtoValidatorIrBaseType =
  (typeof UpdateFieldDtoValidatorIrBaseType)[keyof typeof UpdateFieldDtoValidatorIrBaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFieldDtoValidatorIrBaseType = {
  text: "text",
  number: "number",
  date: "date",
  enum: "enum",
  array: "array",
  checkbox: "checkbox",
  textarea: "textarea",
  time: "time",
  email: "email",
  phone: "phone",
  url: "url",
  signature: "signature",
  image: "image",
} as const;
