/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type UpdateFieldDtoSource = (typeof UpdateFieldDtoSource)[keyof typeof UpdateFieldDtoSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFieldDtoSource = {
  auto: "auto",
  prefill: "prefill",
  derived: "derived",
  manual: "manual",
} as const;
