/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type UpdateFieldDtoValidatorIrRulesItemOneOfSixKind =
  (typeof UpdateFieldDtoValidatorIrRulesItemOneOfSixKind)[keyof typeof UpdateFieldDtoValidatorIrRulesItemOneOfSixKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFieldDtoValidatorIrRulesItemOneOfSixKind = {
  regex: "regex",
} as const;
