/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type UpdateFieldDtoValidatorIrRulesItemOneOfKind =
  (typeof UpdateFieldDtoValidatorIrRulesItemOneOfKind)[keyof typeof UpdateFieldDtoValidatorIrRulesItemOneOfKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFieldDtoValidatorIrRulesItemOneOfKind = {
  required: "required",
  email: "email",
  url: "url",
  plainText: "plainText",
  titleCase: "titleCase",
  trim: "trim",
  dateOnOrAfterToday: "dateOnOrAfterToday",
  dateOnOrBeforeToday: "dateOnOrBeforeToday",
} as const;
