/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { UploadSignatureImageDtoSource } from "./uploadSignatureImageDtoSource";

export interface UploadSignatureImageDto {
  source: UploadSignatureImageDtoSource;
  dataUrl: string;
}
