/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  MagicLinkResponse,
  SignatoryMagicLinkControllerMagicLinkLoginParams,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const signatoryMagicLinkControllerMagicLinkLogin = (
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<MagicLinkResponse>({
    url: `/api/docs/auth/magic-link`,
    method: "GET",
    params,
    signal,
  });
};

export const getSignatoryMagicLinkControllerMagicLinkLoginQueryKey = (
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams
) => {
  return [`/api/docs/auth/magic-link`, ...(params ? [params] : [])] as const;
};

export const getSignatoryMagicLinkControllerMagicLinkLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryMagicLinkControllerMagicLinkLoginQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>
  > = ({ signal }) => signatoryMagicLinkControllerMagicLinkLogin(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryMagicLinkControllerMagicLinkLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>
>;
export type SignatoryMagicLinkControllerMagicLinkLoginQueryError = ErrorResponse;

export function useSignatoryMagicLinkControllerMagicLinkLogin<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params: undefined | SignatoryMagicLinkControllerMagicLinkLoginParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
          TError,
          Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryMagicLinkControllerMagicLinkLogin<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
          TError,
          Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryMagicLinkControllerMagicLinkLogin<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryMagicLinkControllerMagicLinkLogin<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryMagicLinkControllerMagicLinkLoginQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryMagicLinkControllerMagicLinkLoginSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryMagicLinkControllerMagicLinkLoginQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>
  > = ({ signal }) => signatoryMagicLinkControllerMagicLinkLogin(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryMagicLinkControllerMagicLinkLoginSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>
>;
export type SignatoryMagicLinkControllerMagicLinkLoginSuspenseQueryError = ErrorResponse;

export function useSignatoryMagicLinkControllerMagicLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params: undefined | SignatoryMagicLinkControllerMagicLinkLoginParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryMagicLinkControllerMagicLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryMagicLinkControllerMagicLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryMagicLinkControllerMagicLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
  TError = ErrorResponse,
>(
  params?: SignatoryMagicLinkControllerMagicLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryMagicLinkControllerMagicLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryMagicLinkControllerMagicLinkLoginSuspenseQueryOptions(
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
