/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  ErrorResponse,
  SignatoryRequestOtpDto,
  SignatoryRequestOtpResponse,
  SignatoryVerifyOtpDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const authControllerSignatoryLoginRequest = (
  signatoryRequestOtpDto: SignatoryRequestOtpDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<SignatoryRequestOtpResponse>({
    url: `/api/auth/docs/login/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: signatoryRequestOtpDto,
    signal,
  });
};

export const getAuthControllerSignatoryLoginRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignatoryLoginRequest>>,
    TError,
    { data: SignatoryRequestOtpDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignatoryLoginRequest>>,
  TError,
  { data: SignatoryRequestOtpDto },
  TContext
> => {
  const mutationKey = ["authControllerSignatoryLoginRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignatoryLoginRequest>>,
    { data: SignatoryRequestOtpDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignatoryLoginRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignatoryLoginRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignatoryLoginRequest>>
>;
export type AuthControllerSignatoryLoginRequestMutationBody = SignatoryRequestOtpDto;
export type AuthControllerSignatoryLoginRequestMutationError = ErrorResponse;

export const useAuthControllerSignatoryLoginRequest = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignatoryLoginRequest>>,
      TError,
      { data: SignatoryRequestOtpDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignatoryLoginRequest>>,
  TError,
  { data: SignatoryRequestOtpDto },
  TContext
> => {
  const mutationOptions = getAuthControllerSignatoryLoginRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authControllerSignatoryLoginVerify = (
  signatoryVerifyOtpDto: SignatoryVerifyOtpDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/docs/login/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: signatoryVerifyOtpDto,
    signal,
  });
};

export const getAuthControllerSignatoryLoginVerifyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignatoryLoginVerify>>,
    TError,
    { data: SignatoryVerifyOtpDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignatoryLoginVerify>>,
  TError,
  { data: SignatoryVerifyOtpDto },
  TContext
> => {
  const mutationKey = ["authControllerSignatoryLoginVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignatoryLoginVerify>>,
    { data: SignatoryVerifyOtpDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignatoryLoginVerify(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignatoryLoginVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignatoryLoginVerify>>
>;
export type AuthControllerSignatoryLoginVerifyMutationBody = SignatoryVerifyOtpDto;
export type AuthControllerSignatoryLoginVerifyMutationError = ErrorResponse;

export const useAuthControllerSignatoryLoginVerify = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignatoryLoginVerify>>,
      TError,
      { data: SignatoryVerifyOtpDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignatoryLoginVerify>>,
  TError,
  { data: SignatoryVerifyOtpDto },
  TContext
> => {
  const mutationOptions = getAuthControllerSignatoryLoginVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authControllerSignatorySignOut = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/docs/logout`,
    method: "POST",
    signal,
  });
};

export const getAuthControllerSignatorySignOutMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignatorySignOut>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignatorySignOut>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerSignatorySignOut"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignatorySignOut>>,
    void
  > = () => {
    return authControllerSignatorySignOut();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignatorySignOutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignatorySignOut>>
>;

export type AuthControllerSignatorySignOutMutationError = ErrorResponse;

export const useAuthControllerSignatorySignOut = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignatorySignOut>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignatorySignOut>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthControllerSignatorySignOutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
