/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const sesBounceWebhookControllerReceiveBounceEvent = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<null>({
    url: `/api/webhooks/ses/bounce`,
    method: "POST",
    signal,
  });
};

export const getSesBounceWebhookControllerReceiveBounceEventMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sesBounceWebhookControllerReceiveBounceEvent>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sesBounceWebhookControllerReceiveBounceEvent>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["sesBounceWebhookControllerReceiveBounceEvent"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sesBounceWebhookControllerReceiveBounceEvent>>,
    void
  > = () => {
    return sesBounceWebhookControllerReceiveBounceEvent();
  };

  return { mutationFn, ...mutationOptions };
};

export type SesBounceWebhookControllerReceiveBounceEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof sesBounceWebhookControllerReceiveBounceEvent>>
>;

export type SesBounceWebhookControllerReceiveBounceEventMutationError = unknown;

export const useSesBounceWebhookControllerReceiveBounceEvent = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sesBounceWebhookControllerReceiveBounceEvent>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sesBounceWebhookControllerReceiveBounceEvent>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSesBounceWebhookControllerReceiveBounceEventMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
