/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  ErrorResponse,
  MoaDocumentThreadResponse,
  MoaRequestResponse,
  MoaRequestsResponse,
  MoaRespondDto,
  MoaThreadResponse,
  NewCustomMoaRequestDto,
  NewCustomMoaRequestResponse,
  NewStandardMoaRequestDto,
  NewStandardMoaRequestResponse,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const entityMoaControllerGetMine = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<MoaRequestsResponse>({
    url: `/api/entity/moa/mine`,
    method: "GET",
    signal,
  });
};

export const getEntityMoaControllerGetMineQueryKey = () => {
  return [`/api/entity/moa/mine`] as const;
};

export const getEntityMoaControllerGetMineQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEntityMoaControllerGetMineQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof entityMoaControllerGetMine>>> = ({
    signal,
  }) => entityMoaControllerGetMine(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetMineQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetMine>>
>;
export type EntityMoaControllerGetMineQueryError = ErrorResponse;

export function useEntityMoaControllerGetMine<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetMine>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetMine<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetMine>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetMine<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetMine<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetMineQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEntityMoaControllerGetMineSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEntityMoaControllerGetMineQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof entityMoaControllerGetMine>>> = ({
    signal,
  }) => entityMoaControllerGetMine(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetMineSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetMine>>
>;
export type EntityMoaControllerGetMineSuspenseQueryError = ErrorResponse;

export function useEntityMoaControllerGetMineSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetMineSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetMineSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetMineSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetMine>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetMineSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const entityMoaControllerGetLatestMoaRequest = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<MoaRequestResponse>({
    url: `/api/entity/moa/me/latest`,
    method: "GET",
    signal,
  });
};

export const getEntityMoaControllerGetLatestMoaRequestQueryKey = () => {
  return [`/api/entity/moa/me/latest`] as const;
};

export const getEntityMoaControllerGetLatestMoaRequestQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEntityMoaControllerGetLatestMoaRequestQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>
  > = ({ signal }) => entityMoaControllerGetLatestMoaRequest(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetLatestMoaRequestQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>
>;
export type EntityMoaControllerGetLatestMoaRequestQueryError = ErrorResponse;

export function useEntityMoaControllerGetLatestMoaRequest<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetLatestMoaRequest<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetLatestMoaRequest<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetLatestMoaRequest<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetLatestMoaRequestQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEntityMoaControllerGetLatestMoaRequestSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEntityMoaControllerGetLatestMoaRequestQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>
  > = ({ signal }) => entityMoaControllerGetLatestMoaRequest(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetLatestMoaRequestSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>
>;
export type EntityMoaControllerGetLatestMoaRequestSuspenseQueryError = ErrorResponse;

export function useEntityMoaControllerGetLatestMoaRequestSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetLatestMoaRequestSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetLatestMoaRequestSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetLatestMoaRequestSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetLatestMoaRequest>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetLatestMoaRequestSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const entityMoaControllerRequestNewStandard = (
  newStandardMoaRequestDto: NewStandardMoaRequestDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<NewStandardMoaRequestResponse>({
    url: `/api/entity/moa/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: newStandardMoaRequestDto,
    signal,
  });
};

export const getEntityMoaControllerRequestNewStandardMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof entityMoaControllerRequestNewStandard>>,
    TError,
    { data: NewStandardMoaRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof entityMoaControllerRequestNewStandard>>,
  TError,
  { data: NewStandardMoaRequestDto },
  TContext
> => {
  const mutationKey = ["entityMoaControllerRequestNewStandard"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof entityMoaControllerRequestNewStandard>>,
    { data: NewStandardMoaRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return entityMoaControllerRequestNewStandard(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type EntityMoaControllerRequestNewStandardMutationResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerRequestNewStandard>>
>;
export type EntityMoaControllerRequestNewStandardMutationBody = NewStandardMoaRequestDto;
export type EntityMoaControllerRequestNewStandardMutationError = ErrorResponse;

export const useEntityMoaControllerRequestNewStandard = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof entityMoaControllerRequestNewStandard>>,
      TError,
      { data: NewStandardMoaRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof entityMoaControllerRequestNewStandard>>,
  TError,
  { data: NewStandardMoaRequestDto },
  TContext
> => {
  const mutationOptions = getEntityMoaControllerRequestNewStandardMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const entityMoaControllerGetOneThread = (
  id: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<MoaThreadResponse>({
    url: `/api/entity/moa/thread/${id}`,
    method: "GET",
    signal,
  });
};

export const getEntityMoaControllerGetOneThreadQueryKey = (id?: string | undefined | null) => {
  return [`/api/entity/moa/thread/${id}`] as const;
};

export const getEntityMoaControllerGetOneThreadQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEntityMoaControllerGetOneThreadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>> = ({
    signal,
  }) => entityMoaControllerGetOneThread(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetOneThreadQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>
>;
export type EntityMoaControllerGetOneThreadQueryError = ErrorResponse;

export function useEntityMoaControllerGetOneThread<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThread<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThread<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetOneThread<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetOneThreadQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEntityMoaControllerGetOneThreadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEntityMoaControllerGetOneThreadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>> = ({
    signal,
  }) => entityMoaControllerGetOneThread(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetOneThreadSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>
>;
export type EntityMoaControllerGetOneThreadSuspenseQueryError = ErrorResponse;

export function useEntityMoaControllerGetOneThreadSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThreadSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThreadSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetOneThreadSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThread>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetOneThreadSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const entityMoaControllerGetOneThreadLatestDocument = (
  id: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<MoaDocumentThreadResponse>({
    url: `/api/entity/moa/thread/${id}/document`,
    method: "GET",
    signal,
  });
};

export const getEntityMoaControllerGetOneThreadLatestDocumentQueryKey = (
  id?: string | undefined | null
) => {
  return [`/api/entity/moa/thread/${id}/document`] as const;
};

export const getEntityMoaControllerGetOneThreadLatestDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getEntityMoaControllerGetOneThreadLatestDocumentQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>
  > = ({ signal }) => entityMoaControllerGetOneThreadLatestDocument(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetOneThreadLatestDocumentQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>
>;
export type EntityMoaControllerGetOneThreadLatestDocumentQueryError = ErrorResponse;

export function useEntityMoaControllerGetOneThreadLatestDocument<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThreadLatestDocument<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
          TError,
          Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThreadLatestDocument<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetOneThreadLatestDocument<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetOneThreadLatestDocumentQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEntityMoaControllerGetOneThreadLatestDocumentSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getEntityMoaControllerGetOneThreadLatestDocumentQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>
  > = ({ signal }) => entityMoaControllerGetOneThreadLatestDocument(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EntityMoaControllerGetOneThreadLatestDocumentSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>
>;
export type EntityMoaControllerGetOneThreadLatestDocumentSuspenseQueryError = ErrorResponse;

export function useEntityMoaControllerGetOneThreadLatestDocumentSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThreadLatestDocumentSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEntityMoaControllerGetOneThreadLatestDocumentSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useEntityMoaControllerGetOneThreadLatestDocumentSuspense<
  TData = Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof entityMoaControllerGetOneThreadLatestDocument>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEntityMoaControllerGetOneThreadLatestDocumentSuspenseQueryOptions(
    id,
    options
  );

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const entityMoaControllerRequestNewCustom = (
  newCustomMoaRequestDto: NewCustomMoaRequestDto,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`school_id`, newCustomMoaRequestDto.school_id);
  formData.append(`reason`, newCustomMoaRequestDto.reason);
  formData.append(`proposed_moa`, newCustomMoaRequestDto.proposed_moa);

  return preconfiguredAxiosFunction<NewCustomMoaRequestResponse>({
    url: `/api/entity/moa/request-custom`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getEntityMoaControllerRequestNewCustomMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof entityMoaControllerRequestNewCustom>>,
    TError,
    { data: NewCustomMoaRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof entityMoaControllerRequestNewCustom>>,
  TError,
  { data: NewCustomMoaRequestDto },
  TContext
> => {
  const mutationKey = ["entityMoaControllerRequestNewCustom"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof entityMoaControllerRequestNewCustom>>,
    { data: NewCustomMoaRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return entityMoaControllerRequestNewCustom(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type EntityMoaControllerRequestNewCustomMutationResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerRequestNewCustom>>
>;
export type EntityMoaControllerRequestNewCustomMutationBody = NewCustomMoaRequestDto;
export type EntityMoaControllerRequestNewCustomMutationError = ErrorResponse;

export const useEntityMoaControllerRequestNewCustom = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof entityMoaControllerRequestNewCustom>>,
      TError,
      { data: NewCustomMoaRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof entityMoaControllerRequestNewCustom>>,
  TError,
  { data: NewCustomMoaRequestDto },
  TContext
> => {
  const mutationOptions = getEntityMoaControllerRequestNewCustomMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const entityMoaControllerRespond = (
  id: string | undefined | null,
  moaRespondDto: MoaRespondDto,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`message`, moaRespondDto.message);
  if (moaRespondDto.revised_moa !== undefined) {
    formData.append(`revised_moa`, moaRespondDto.revised_moa);
  }

  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/entity/moa/${id}/respond`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getEntityMoaControllerRespondMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof entityMoaControllerRespond>>,
    TError,
    { id: string | undefined | null; data: MoaRespondDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof entityMoaControllerRespond>>,
  TError,
  { id: string | undefined | null; data: MoaRespondDto },
  TContext
> => {
  const mutationKey = ["entityMoaControllerRespond"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof entityMoaControllerRespond>>,
    { id: string | undefined | null; data: MoaRespondDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return entityMoaControllerRespond(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type EntityMoaControllerRespondMutationResult = NonNullable<
  Awaited<ReturnType<typeof entityMoaControllerRespond>>
>;
export type EntityMoaControllerRespondMutationBody = MoaRespondDto;
export type EntityMoaControllerRespondMutationError = ErrorResponse;

export const useEntityMoaControllerRespond = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof entityMoaControllerRespond>>,
      TError,
      { id: string | undefined | null; data: MoaRespondDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof entityMoaControllerRespond>>,
  TError,
  { id: string | undefined | null; data: MoaRespondDto },
  TContext
> => {
  const mutationOptions = getEntityMoaControllerRespondMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
