/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { ErrorResponse, FormFilloutProcessResult, ProcessCallbackDto } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const processCallbackControllerProcessCallback = (
  processCallbackDto: ProcessCallbackDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<FormFilloutProcessResult>({
    url: `/api/callback`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: processCallbackDto,
    signal,
  });
};

export const getProcessCallbackControllerProcessCallbackMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof processCallbackControllerProcessCallback>>,
    TError,
    { data: ProcessCallbackDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof processCallbackControllerProcessCallback>>,
  TError,
  { data: ProcessCallbackDto },
  TContext
> => {
  const mutationKey = ["processCallbackControllerProcessCallback"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof processCallbackControllerProcessCallback>>,
    { data: ProcessCallbackDto }
  > = (props) => {
    const { data } = props ?? {};

    return processCallbackControllerProcessCallback(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProcessCallbackControllerProcessCallbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof processCallbackControllerProcessCallback>>
>;
export type ProcessCallbackControllerProcessCallbackMutationBody = ProcessCallbackDto;
export type ProcessCallbackControllerProcessCallbackMutationError = ErrorResponse;

export const useProcessCallbackControllerProcessCallback = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof processCallbackControllerProcessCallback>>,
      TError,
      { data: ProcessCallbackDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof processCallbackControllerProcessCallback>>,
  TError,
  { data: ProcessCallbackDto },
  TContext
> => {
  const mutationOptions = getProcessCallbackControllerProcessCallbackMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const processCallbackControllerInternalProcessCallback = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<FormFilloutProcessResult>({
    url: `/api/callback/__internal`,
    method: "POST",
    signal,
  });
};

export const getProcessCallbackControllerInternalProcessCallbackMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof processCallbackControllerInternalProcessCallback>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof processCallbackControllerInternalProcessCallback>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["processCallbackControllerInternalProcessCallback"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof processCallbackControllerInternalProcessCallback>>,
    void
  > = () => {
    return processCallbackControllerInternalProcessCallback();
  };

  return { mutationFn, ...mutationOptions };
};

export type ProcessCallbackControllerInternalProcessCallbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof processCallbackControllerInternalProcessCallback>>
>;

export type ProcessCallbackControllerInternalProcessCallbackMutationError = ErrorResponse;

export const useProcessCallbackControllerInternalProcessCallback = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof processCallbackControllerInternalProcessCallback>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof processCallbackControllerInternalProcessCallback>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getProcessCallbackControllerInternalProcessCallbackMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
